# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

target 'iosApp' do
    pod 'SwiftLint'
end

target 'iosAppTests' do
    inherit! :search_paths
    # Pods for testing
  end


